=== KishoreKaushal/XMLPropertyTree/sample.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:element name="StartDate" type="xs:date" />
    <xs:element name="StartTime" type="xs:time" />
    <xs:element name="Duration" type="xs:duration" />
    <xs:element name="UniqueID" type="xs:string" />
    <xs:element name="StudyID" type="xs:string" />
    <xs:element name="SiteID" type="xs:string" />
    <xs:element name="InvestigatorID" type="xs:string" />
    <xs:element name="UniqueSubjectID" type="xs:string" />
    <xs:element name="SubjectID" type="xs:string" />
    <xs:element name="SubjectAge" type="xs:duration" />
    <xs:element name="SubjectRace" type="xs:string" />
    <xs:element name="TreatmentCode" type="xs:string" />
    <xs:element name="TreatmentGroup" type="xs:string" />
    <xs:element name="Country" type="xs:string" />
    <xs:element name="VisitNumber" type="xs:string" />
    <xs:element name="VisitDay" type="xs:string" />
    <xs:element name="VisitName" type="xs:string" />
    <xs:element name="DisplayText" type="xs:string" />
    <xs:element name="Comment" type="xs:string" />
    <xs:element name="TimeSinceSessionStart" type="xs:duration" default="P0Y"/>
    <xs:element name="TimeDuration" type="xs:duration" />
    <xs:element name="Type" type="xs:string" />
    <xs:element name="Manufacturer" type="xs:string" />
    <xs:element name="Model" type="xs:string" />
    <xs:element name="SerialNumber" type="xs:string" />
    <xs:element name="DeviceID" type="xs:string" />
    <xs:element name="SoftwareVersion" type="xs:string" />
    <xs:element name="XOffset" type="xs:float" default="0"/>
    <xs:element name="Connected" type="xs:boolean" default="true" />
    <xs:element name="AspectRatio" type="xs:float" default="1" />
    <xs:element name="BeginningValue" type="xs:float" />
    <xs:element name="EndingValue" type="xs:float" />
    <xs:element name="Unit" type="xs:string" />
    <xs:element name="MinorTickInterval" type="xs:float" />
    <xs:element name="MajorTickInterval" type="xs:float" />
    <xs:element name="LogScale" type="xs:boolean" default="false" />
    <xs:element name="RealTime" type="xs:boolean" default="false" />
    <xs:element name="Scale" type="xs:float" default="1" />
    <xs:element name="Offset" type="xs:float" default="0" />
    <xs:element name="InitialValue" type="xs:float" />
    <xs:element name="Increment" type="xs:float" />
    <xs:element name="YValue" type="xs:float" />
    <xs:element name="XValue" type="xs:float" />

    <xs:element name="RecordingSessionPlots">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="StartDate" />
                <xs:element ref="StartTime" />
                <xs:element ref="Duration" minOccurs="0" />
                <xs:element ref="UniqueID" minOccurs="0"/>
                <xs:element name="PlotGroup" type="PlotGroupType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="TrialIdentifiers" type="TrialIdentifiersType" minOccurs="0" />
                <xs:element name="RecordingDevice" type="RecordingDeviceType" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="FormatVersion" fixed="1.0" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="TrialIdentifiersType">
        <xs:sequence>
            <xs:element ref="StudyID" />
            <xs:element ref="SiteID" minOccurs="0" />
            <xs:element ref="InvestigatorID" minOccurs="0"/>
            <xs:element ref="UniqueSubjectID" minOccurs="0"/>
            <xs:element ref="SubjectID" minOccurs="0"/>
            <xs:element ref="SubjectAge" minOccurs="0"/>
            <xs:element name="SubjectSex" type="SexType" minOccurs="0"/>
            <xs:element ref="SubjectRace" minOccurs="0" />
            <xs:element ref="TreatmentCode" minOccurs="0" />
            <xs:element ref="TreatmentGroup" minOccurs="0" />
            <xs:element ref="Country" minOccurs="0" />
            <xs:element ref="VisitNumber" minOccurs="0" />
            <xs:element ref="VisitDay" minOccurs="0" />
            <xs:element ref="VisitName" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RecordingDeviceType">
        <xs:sequence>
            <xs:element name="Type" minOccurs="0"/>
            <xs:element name="Manufacturer" minOccurs="0"/>
            <xs:element name="Model" minOccurs="0"/>
            <xs:element name="SerialNumber" minOccurs="0"/>
            <xs:element name="DeviceID" minOccurs="0"/>
            <xs:element name="SoftwareVersion" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PlotGroupType">
        <xs:sequence>
            <xs:element name="Label" type="PlotGroupLabelType" />
            <xs:element ref="Comment" minOccurs="0" />
            <xs:element ref="TimeSinceSessionStart" />
            <xs:element ref="TimeDuration" minOccurs="0" />
            <xs:element name="XAxisDomain" type="XAxisDomainType" />
            <xs:element name="XYPlot" type="XYPlotType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="XAxisNotation" type="AxisNotationType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    

    <xs:complexType name="PointNotationType">
        <xs:sequence>
            <xs:element ref="XValue"/>
            <xs:element ref="YValue"/>
            <xs:element name="Label" type="PointNotationLabelType" />
            <xs:element ref="Comment" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XAxisDomainType">
        <xs:sequence>
            <xs:element ref="Unit"/>
            <xs:element name="Label" type="XAxisDomainLabelType" />
            <xs:element ref="MinorTickInterval" minOccurs="0" />
            <xs:element ref="MajorTickInterval" minOccurs="0" />
            <xs:element ref="LogScale" />
            <xs:element ref="RealTime" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AxisNotationType">
        <xs:sequence>
            <xs:element ref="BeginningValue" />
            <xs:element ref="EndingValue" minOccurs="0" />
            <xs:element name="Label" type="AxisNotationLabelType" />
            <xs:element ref="Comment" minOccurs="0" /> 
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ValuesType">
        <xs:sequence>
            <xs:element ref="Scale" />
            <xs:element ref="Offset" />
            <xs:choice minOccurs="0">
                <xs:sequence>
                    <xs:element ref="InitialValue" minOccurs="0" />
                    <xs:element ref="Increment" minOccurs="0" />    
                </xs:sequence>

                <xs:element name="ValuesList" type="ValuesListType" minOccurs="0"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XYPlotType">
        <xs:sequence>
            <xs:element name="Label" type="XYPlotLabelType" />
            <xs:element ref="Comment" minOccurs="0" />
            <xs:element ref="XOffset" />
            <xs:element ref="Connected" />
            <xs:element ref="AspectRatio" />
            <xs:element name="YAxisDomain" type="YAxisDomainType" />
            <xs:element name="XValues" type="ValuesType" />
            <xs:element name="YValues" type="ValuesType" />
            <xs:element name="PointNotation" type="PointNotationType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="XAxisNotation" type="AxisNotationType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="YAxisNotation" type="AxisNotationType" minOccurs="0" maxOccurs="unbounded"/> 
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="YAxisDomainType">
        <xs:sequence>
            <xs:element ref="Unit" />
            <xs:element name="Label" type="YAxisDomainLabelType" />
            <xs:element ref="MinorTickInterval" minOccurs="0" />
            <xs:element ref="MajorTickInterval" minOccurs="0" />
            <xs:element ref="LogScale" /> 
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="ValuesListType">
        <xs:list itemType="xs:float"/>
    </xs:simpleType>

    <xs:simpleType name="SexType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M">
                <xs:annotation>
                    <xs:documentation>Male</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="F">
                <xs:annotation>
                    <xs:documentation>Female</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="PlotGroupLabelType">
        <xs:sequence>
            <xs:element ref="DisplayText" />
            <xs:element name="Code" type="PlotGroupLabelCodeType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="PlotGroupLabelCodeType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="AxisNotationLabelType">
        <xs:sequence>
            <xs:element ref="DisplayText"/>
            <xs:element name="Code" type="AxisNotationLabelCodeType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="AxisNotationLabelCodeType">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:complexType name="PointNotationLabelType">
        <xs:sequence>
            <xs:element ref="DisplayText"/>
            <xs:element name="Code" type="PointNotationLabelCodeType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="PointNotationLabelCodeType">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:complexType name="XAxisDomainLabelType">
        <xs:sequence>
            <xs:element ref="DisplayText"/>
            <xs:element name="Code" type="XAxisDomainLabelCodeType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="XAxisDomainLabelCodeType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="YAxisDomainLabelType">
        <xs:sequence>
            <xs:element ref="DisplayText"/>
            <xs:element name="Code" type="YAxisDomainLabelCodeType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="YAxisDomainLabelCodeType">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:complexType name="XYPlotLabelType">
        <xs:sequence>
            <xs:element ref="DisplayText"/>
            <xs:element name="Code" type="XYPlotLabelCodeType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="XYPlotLabelCodeType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
</xs:schema>

=== KishoreKaushal/XMLPropertyTree/sample.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<RecordingSessionPlots xsi:noNamespaceSchemaLocation="sample.xsd" FormatVersion="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <StartDate>1994-12-19</StartDate>
  <StartTime>08:19:13.30</StartTime>
  <Duration>P6Y9M2DT23H9M58.89S</Duration>
  <UniqueID>string</UniqueID>
  <PlotGroup>
    <Label>
      <DisplayText>string</DisplayText>
      <Code>string</Code>
    </Label>
    <Comment>string</Comment>
    <TimeSinceSessionStart>P0Y</TimeSinceSessionStart>
    <TimeDuration>P1Y2M27DT23H55M54.35S</TimeDuration>
    <XAxisDomain>
      <Unit>string</Unit>
      <Label>
        <DisplayText>string</DisplayText>
      </Label>
      <MinorTickInterval>-14044999999999.8</MinorTickInterval>
      <MajorTickInterval>24427200000000.2</MajorTickInterval>
      <LogScale>true</LogScale>
      <RealTime>1</RealTime>
    </XAxisDomain>
    <XYPlot>
      <Label>
        <DisplayText>string</DisplayText>
      </Label>
      <Comment>string</Comment>
      <XOffset>0</XOffset>
      <Connected>true</Connected>
      <AspectRatio>1</AspectRatio>
      <YAxisDomain>
        <Unit>string</Unit>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
        <LogScale>false</LogScale>
      </YAxisDomain>
      <XValues>
        <Scale>1</Scale>
        <Offset>0</Offset>
      </XValues>
      <YValues>
        <Scale>1</Scale>
        <Offset>0</Offset>
      </YValues>
      <PointNotation>
        <XValue>-35569399999999.8</XValue>
        <YValue>-29805999999999.8</YValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </PointNotation>
      <PointNotation>
        <XValue>-12333899999999.8</XValue>
        <YValue>-27887399999999.8</YValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </PointNotation>
      <PointNotation>
        <XValue>42647000000000.2</XValue>
        <YValue>23028000000000.2</YValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </PointNotation>
      <PointNotation>
        <XValue>-36068899999999.8</XValue>
        <YValue>34285300000000.2</YValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </PointNotation>
      <YAxisNotation>
        <BeginningValue>-28454499999999.8</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </YAxisNotation>
      <YAxisNotation>
        <BeginningValue>23960800000000.2</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </YAxisNotation>
      <YAxisNotation>
        <BeginningValue>-24498799999999.8</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </YAxisNotation>
    </XYPlot>
    <XYPlot>
      <Label>
        <DisplayText>string</DisplayText>
      </Label>
      <Comment>string</Comment>
      <XOffset>0</XOffset>
      <Connected>false</Connected>
      <AspectRatio>1</AspectRatio>
      <YAxisDomain>
        <Unit>string</Unit>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
        <LogScale>0</LogScale>
      </YAxisDomain>
      <XValues>
        <Scale>1</Scale>
        <Offset>0</Offset>
      </XValues>
      <YValues>
        <Scale>1</Scale>
        <Offset>0</Offset>
      </YValues>
      <PointNotation>
        <XValue>5598500000000.24</XValue>
        <YValue>-4606799999999.76</YValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </PointNotation>
      <PointNotation>
        <XValue>2450100000000.23</XValue>
        <YValue>-35426699999999.8</YValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </PointNotation>
      <XAxisNotation>
        <BeginningValue>-1074699999999.77</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </XAxisNotation>
      <XAxisNotation>
        <BeginningValue>28444700000000.2</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </XAxisNotation>
      <XAxisNotation>
        <BeginningValue>-18804999999999.8</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </XAxisNotation>
    </XYPlot>
    <XYPlot>
      <Label>
        <DisplayText>string</DisplayText>
      </Label>
      <Comment>string</Comment>
      <XOffset>0</XOffset>
      <Connected>true</Connected>
      <AspectRatio>1</AspectRatio>
      <YAxisDomain>
        <Unit>string</Unit>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
        <LogScale>true</LogScale>
      </YAxisDomain>
      <XValues>
        <Scale>1</Scale>
        <Offset>0</Offset>
      </XValues>
      <YValues>
        <Scale>1</Scale>
        <Offset>0</Offset>
      </YValues>
      <PointNotation>
        <XValue>-25248399999999.8</XValue>
        <YValue>-20669499999999.8</YValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </PointNotation>
      <PointNotation>
        <XValue>-41177499999999.8</XValue>
        <YValue>-31452799999999.8</YValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </PointNotation>
    </XYPlot>
    <XAxisNotation>
      <BeginningValue>-18235199999999.8</BeginningValue>
      <EndingValue>12493100000000.2</EndingValue>
      <Label>
        <DisplayText>string</DisplayText>
      </Label>
    </XAxisNotation>
    <XAxisNotation>
      <BeginningValue>25079500000000.2</BeginningValue>
      <Label>
        <DisplayText>string</DisplayText>
      </Label>
      <Comment>string</Comment>
    </XAxisNotation>
  </PlotGroup>
  <PlotGroup>
    <Label>
      <DisplayText>string</DisplayText>
    </Label>
    <Comment>string</Comment>
    <TimeSinceSessionStart>P0Y</TimeSinceSessionStart>
    <TimeDuration>P6Y6M14DT0H10M49.15S</TimeDuration>
    <XAxisDomain>
      <Unit>string</Unit>
      <Label>
        <DisplayText>string</DisplayText>
      </Label>
      <MinorTickInterval>43937200000000.2</MinorTickInterval>
      <MajorTickInterval>-6532399999999.76</MajorTickInterval>
      <LogScale>1</LogScale>
      <RealTime>0</RealTime>
    </XAxisDomain>
    <XYPlot>
      <Label>
        <DisplayText>string</DisplayText>
      </Label>
      <Comment>string</Comment>
      <XOffset>0</XOffset>
      <Connected>true</Connected>
      <AspectRatio>1</AspectRatio>
      <YAxisDomain>
        <Unit>string</Unit>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
        <LogScale>1</LogScale>
      </YAxisDomain>
      <XValues>
        <Scale>1</Scale>
        <Offset>0</Offset>
      </XValues>
      <YValues>
        <Scale>1</Scale>
        <Offset>0</Offset>
      </YValues>
      <PointNotation>
        <XValue>36655600000000.2</XValue>
        <YValue>27446000000000.2</YValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </PointNotation>
      <PointNotation>
        <XValue>-3148899999999.77</XValue>
        <YValue>37871200000000.2</YValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </PointNotation>
      <XAxisNotation>
        <BeginningValue>-38499899999999.8</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </XAxisNotation>
      <XAxisNotation>
        <BeginningValue>-49546299999999.8</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </XAxisNotation>
      <XAxisNotation>
        <BeginningValue>49628700000000.2</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </XAxisNotation>
      <XAxisNotation>
        <BeginningValue>977000000000.235</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </XAxisNotation>
      <YAxisNotation>
        <BeginningValue>3036500000000.23</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </YAxisNotation>
      <YAxisNotation>
        <BeginningValue>20332300000000.2</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </YAxisNotation>
      <YAxisNotation>
        <BeginningValue>23879000000000.2</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </YAxisNotation>
    </XYPlot>
    <XYPlot>
      <Label>
        <DisplayText>string</DisplayText>
      </Label>
      <Comment>string</Comment>
      <XOffset>0</XOffset>
      <Connected>1</Connected>
      <AspectRatio>1</AspectRatio>
      <YAxisDomain>
        <Unit>string</Unit>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
        <LogScale>false</LogScale>
      </YAxisDomain>
      <XValues>
        <Scale>1</Scale>
        <Offset>0</Offset>
      </XValues>
      <YValues>
        <Scale>1</Scale>
        <Offset>0</Offset>
      </YValues>
      <XAxisNotation>
        <BeginningValue>9745000000000.23</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </XAxisNotation>
      <XAxisNotation>
        <BeginningValue>20621500000000.2</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </XAxisNotation>
      <XAxisNotation>
        <BeginningValue>9914000000000.23</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </XAxisNotation>
      <YAxisNotation>
        <BeginningValue>-46087099999999.8</BeginningValue>
        <Label>
          <DisplayText>string</DisplayText>
        </Label>
      </YAxisNotation>
      <YAxisNotation>
